name: Publish / Deploy ğŸš€

on:
 workflow_dispatch:
 push:
    branches:
    - production

env:
 AZURE_WEBAPP_NAME: infinet-code-dojo
 AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
 deploy-to-prod:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET ğŸ› ï¸
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore ğŸ“¦
        run: dotnet restore
        
      - name: Build ğŸ—ï¸
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish ğŸ“¦
        run: dotnet publish --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment ğŸš€
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
