name: Pull Request Checks ğŸš€

on:
 pull_request:
    branches: [development, production]

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ“¦
        uses: actions/checkout@v2

      - name: Setup .NET ğŸ› ï¸
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Format the code ğŸ¨
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: Restore dependencies ğŸ“š
        run: dotnet restore --disable-parallel

      - name: Build the solution ğŸ—ï¸
        run: dotnet build --no-restore

      - name: Run all tests ğŸ§ª
        run: dotnet test --no-build --verbosity normal --no-restore
